name: build and release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
jobs:

  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
        cache-dependency-path: go.sum

    - name: Build 
      run: |
        TAG_NAME="bin"
        NAME="$(date -Iseconds -u)"
        export LDFLAGS="${LDFLAGS} -X spaceship/cmd.Version=${NAME}"
        echo "TAG_NAME=${TAG_NAME}" >> "$GITHUB_ENV"
        echo "NAME=${NAME}" >> "$GITHUB_ENV"
        bash build.sh

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: "bin/*"
          tag_name: ${{ env.TAG_NAME }}
          prerelease: false
          name: "${{ env.NAME }}"
          body: "## ⚠ Only the binaries are up to date"
